### PR TITLE
add detector, experiment and collider useful resources

### PR DESCRIPTION
**Pull request by mohshbool**

### CODE REVIEW

**Comment by mohshbool** [comment]
Please note that I did NOT commit the new build under `_/build` as it should be built before deployment

**Review by katilp — CHANGES_REQUESTED** [review]
Thanks a lot! Looking at it now, I think it would be good to have them in this order: 1) the collider 2) the experiment 3) the detector 4) 12 steps 5) Higgs. Would you change them so? Thanks!

**Comment by mohshbool** [comment]
> Thanks a lot! Looking at it now, I think it would be good to have them in this order: 1) the collider 2) the experiment 3) the detector 4) 12 steps 5) Higgs. Would you change them so? Thanks!

Done

**Review by katilp — APPROVED** [review]
Looks good to me, thanks!

**Pull request merged**
